org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Duser.language=en -Duser.country=US
android.useAndroidX=true
android.enableJetifier=true
kotlin.daemon.jvm.options=-Xmx2g -Duser.language=en -Duser.country=US
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true