name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # استخدام Xcode 16.2 الذي يتعرف رسمياً على كلمة sending في Firebase
      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup iOS Environment
        run: |
          rm -rf ios macos/ios
          flutter config --no-enable-swift-package-manager
          flutter create --platforms=ios --org com.salaapp .
          sed -i '' "s/# platform :ios, '.*'/platform :ios, '15.0'/g" ios/Podfile
          sed -i '' "s/platform :ios, '.*'/platform :ios, '15.0'/g" ios/Podfile

      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS Application
        run: flutter build ios --release --no-codesign

      - name: Create IPA Package
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r -q app-release.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sala-app-release
          path: app-release.ipa
